version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:MYu1190@db:5432/echomeet_db
      GOOGLE_APPLICATION_CREDENTIALS: /audioechomeet-14d421656842.json
      TRANSCRIPTION_API: /audioechomeet-14d421656842.json
    volumes:
      - /home/leandrojunior2326/audioechomeet-14d421656842.json:/audioechomeet-14d421656842.json
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MYu1190
      POSTGRES_DB: echomeet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
